version: "3.7"

services:

  file_bearer_app:
    volumes:
      - ./:/app
    container_name: file_bearer_app
    restart: unless-stopped
    build: ./
    command: sh -c "python manage.py collectstatic --noinpu && python manage.py migrate && uvicorn price_manager_project.asgi:application --host 0.0.0.0 --port 8000"
      - ./:/usr/src/app/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8001:8001"
