version: "3.7"

services:

  file_bearer_app:
    volumes:
      - ./:/app
    container_name: file_bearer_app
    restart: unless-stopped
    build: ./
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8001"
      - ./:/usr/src/app/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8001:8001"
